// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: rpc/oauth2.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthStyle represents different styles of authentication
type OAuth2_AuthStyle int32

const (
	OAuth2_AUTH_STYLE_UNSPECIFIED OAuth2_AuthStyle = 0
	OAuth2_AUTH_STYLE_AUTO_DETECT OAuth2_AuthStyle = 1
	OAuth2_AUTH_STYLE_IN_HEADER   OAuth2_AuthStyle = 2
	OAuth2_AUTH_STYLE_IN_PARAMS   OAuth2_AuthStyle = 3
)

// Enum value maps for OAuth2_AuthStyle.
var (
	OAuth2_AuthStyle_name = map[int32]string{
		0: "AUTH_STYLE_UNSPECIFIED",
		1: "AUTH_STYLE_AUTO_DETECT",
		2: "AUTH_STYLE_IN_HEADER",
		3: "AUTH_STYLE_IN_PARAMS",
	}
	OAuth2_AuthStyle_value = map[string]int32{
		"AUTH_STYLE_UNSPECIFIED": 0,
		"AUTH_STYLE_AUTO_DETECT": 1,
		"AUTH_STYLE_IN_HEADER":   2,
		"AUTH_STYLE_IN_PARAMS":   3,
	}
)

func (x OAuth2_AuthStyle) Enum() *OAuth2_AuthStyle {
	p := new(OAuth2_AuthStyle)
	*p = x
	return p
}

func (x OAuth2_AuthStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuth2_AuthStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_oauth2_proto_enumTypes[0].Descriptor()
}

func (OAuth2_AuthStyle) Type() protoreflect.EnumType {
	return &file_rpc_oauth2_proto_enumTypes[0]
}

func (x OAuth2_AuthStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuth2_AuthStyle.Descriptor instead.
func (OAuth2_AuthStyle) EnumDescriptor() ([]byte, []int) {
	return file_rpc_oauth2_proto_rawDescGZIP(), []int{0, 0}
}

type OAuth2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *OAuth2_Config         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Token         *OAuth2_Token          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2) Reset() {
	*x = OAuth2{}
	mi := &file_rpc_oauth2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2) ProtoMessage() {}

func (x *OAuth2) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_oauth2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2.ProtoReflect.Descriptor instead.
func (*OAuth2) Descriptor() ([]byte, []int) {
	return file_rpc_oauth2_proto_rawDescGZIP(), []int{0}
}

func (x *OAuth2) GetConfig() *OAuth2_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *OAuth2) GetToken() *OAuth2_Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Config represents the OAuth2 configuration
type OAuth2_Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ClientID is the application's ID.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// ClientSecret is the application's secret.
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	// Endpoint contains the resource server's token endpoint
	// URLs. These are constants specific to each server and are
	// often available via site-specific packages, such as
	// google.Endpoint or github.Endpoint.
	Endpoint *OAuth2_Endpoint `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// RedirectURL is the URL to redirect users going through
	// the OAuth flow, after the resource owner's URLs.
	RedirectUrl string `protobuf:"bytes,4,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	// Scope specifies optional requested permissions.
	Scopes        []string `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2_Config) Reset() {
	*x = OAuth2_Config{}
	mi := &file_rpc_oauth2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2_Config) ProtoMessage() {}

func (x *OAuth2_Config) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_oauth2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2_Config.ProtoReflect.Descriptor instead.
func (*OAuth2_Config) Descriptor() ([]byte, []int) {
	return file_rpc_oauth2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OAuth2_Config) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuth2_Config) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuth2_Config) GetEndpoint() *OAuth2_Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *OAuth2_Config) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *OAuth2_Config) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// Endpoint represents an OAuth 2.0 provider's authorization and token
// endpoint URLs.
type OAuth2_Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	DeviceAuthUrl string                 `protobuf:"bytes,2,opt,name=device_auth_url,json=deviceAuthUrl,proto3" json:"device_auth_url,omitempty"`
	TokenUrl      string                 `protobuf:"bytes,3,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	// AuthStyle optionally specifies how the endpoint wants the
	// client ID & client secret sent. The zero value means to
	// auto-detect.
	AuthStyle     OAuth2_AuthStyle `protobuf:"varint,4,opt,name=auth_style,json=authStyle,proto3,enum=dataq.OAuth2_AuthStyle" json:"auth_style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2_Endpoint) Reset() {
	*x = OAuth2_Endpoint{}
	mi := &file_rpc_oauth2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2_Endpoint) ProtoMessage() {}

func (x *OAuth2_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_oauth2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2_Endpoint.ProtoReflect.Descriptor instead.
func (*OAuth2_Endpoint) Descriptor() ([]byte, []int) {
	return file_rpc_oauth2_proto_rawDescGZIP(), []int{0, 1}
}

func (x *OAuth2_Endpoint) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *OAuth2_Endpoint) GetDeviceAuthUrl() string {
	if x != nil {
		return x.DeviceAuthUrl
	}
	return ""
}

func (x *OAuth2_Endpoint) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OAuth2_Endpoint) GetAuthStyle() OAuth2_AuthStyle {
	if x != nil {
		return x.AuthStyle
	}
	return OAuth2_AUTH_STYLE_UNSPECIFIED
}

// Token represents the credentials used to authorize
// the requests to access protected resources on the OAuth 2.0
// provider's backend.
//
// Most users of this package should not access fields of Token
// directly. They're exported mostly for use by related packages
// implementing derivative OAuth2 flows.
type OAuth2_Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AccessToken is the token that authorizes and authenticates
	// the requests.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// TokenType is the type of token.
	// The Type method returns either this or "Bearer", the default.
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// RefreshToken is a token that's used by the application
	// (as opposed to the user) to refresh the access token
	// if it expires.
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Expiry is the optional expiration time of the access token.
	//
	// If zero, TokenSource implementations will reuse the same
	// token forever and RefreshToken or equivalent
	// mechanisms for that TokenSource will not be used.
	Expiry int64 `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// ExpiresIn is the OAuth2 wire format "expires_in" field,
	// which specifies how many seconds later the token expires,
	// relative to an unknown time base approximately around "now".
	// It is the application's responsibility to populate
	// `Expiry` from `ExpiresIn` when required.
	ExpiresIn     int64 `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2_Token) Reset() {
	*x = OAuth2_Token{}
	mi := &file_rpc_oauth2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2_Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2_Token) ProtoMessage() {}

func (x *OAuth2_Token) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_oauth2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2_Token.ProtoReflect.Descriptor instead.
func (*OAuth2_Token) Descriptor() ([]byte, []int) {
	return file_rpc_oauth2_proto_rawDescGZIP(), []int{0, 2}
}

func (x *OAuth2_Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2_Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuth2_Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2_Token) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *OAuth2_Token) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_rpc_oauth2_proto protoreflect.FileDescriptor

var file_rpc_oauth2_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x64, 0x61, 0x74, 0x61, 0x71, 0x22, 0xe3, 0x05, 0x0a, 0x06, 0x4f, 0x41,
	0x75, 0x74, 0x68, 0x32, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x71, 0x2e, 0x4f, 0x41, 0x75,
	0x74, 0x68, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x71, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0xb9, 0x01,
	0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x71, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x2e, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x1a, 0xa2, 0x01, 0x0a, 0x08, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x55, 0x72,
	0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x74, 0x79, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x71, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74,
	0x79, 0x6c, 0x65, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x1a, 0xa5,
	0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x5f, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x22, 0x77, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74,
	0x79, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x59, 0x4c,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x41, 0x55,
	0x54, 0x4f, 0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x41,
	0x55, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x48, 0x45, 0x41,
	0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x53, 0x54,
	0x59, 0x4c, 0x45, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x10, 0x03, 0x42,
	0x17, 0x5a, 0x15, 0x67, 0x6f, 0x2e, 0x71, 0x75, 0x69, 0x6e, 0x6e, 0x2e, 0x69, 0x6f, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x71, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_oauth2_proto_rawDescOnce sync.Once
	file_rpc_oauth2_proto_rawDescData = file_rpc_oauth2_proto_rawDesc
)

func file_rpc_oauth2_proto_rawDescGZIP() []byte {
	file_rpc_oauth2_proto_rawDescOnce.Do(func() {
		file_rpc_oauth2_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_oauth2_proto_rawDescData)
	})
	return file_rpc_oauth2_proto_rawDescData
}

var file_rpc_oauth2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_oauth2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_oauth2_proto_goTypes = []any{
	(OAuth2_AuthStyle)(0),   // 0: dataq.OAuth2.AuthStyle
	(*OAuth2)(nil),          // 1: dataq.OAuth2
	(*OAuth2_Config)(nil),   // 2: dataq.OAuth2.Config
	(*OAuth2_Endpoint)(nil), // 3: dataq.OAuth2.Endpoint
	(*OAuth2_Token)(nil),    // 4: dataq.OAuth2.Token
}
var file_rpc_oauth2_proto_depIdxs = []int32{
	2, // 0: dataq.OAuth2.config:type_name -> dataq.OAuth2.Config
	4, // 1: dataq.OAuth2.token:type_name -> dataq.OAuth2.Token
	3, // 2: dataq.OAuth2.Config.endpoint:type_name -> dataq.OAuth2.Endpoint
	0, // 3: dataq.OAuth2.Endpoint.auth_style:type_name -> dataq.OAuth2.AuthStyle
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_oauth2_proto_init() }
func file_rpc_oauth2_proto_init() {
	if File_rpc_oauth2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_oauth2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_oauth2_proto_goTypes,
		DependencyIndexes: file_rpc_oauth2_proto_depIdxs,
		EnumInfos:         file_rpc_oauth2_proto_enumTypes,
		MessageInfos:      file_rpc_oauth2_proto_msgTypes,
	}.Build()
	File_rpc_oauth2_proto = out.File
	file_rpc_oauth2_proto_rawDesc = nil
	file_rpc_oauth2_proto_goTypes = nil
	file_rpc_oauth2_proto_depIdxs = nil
}
