// Code generated by ccf. DO NOT EDIT.
package router

import (
	"github.com/labstack/echo/v4"
	"go.quinn.io/dataq/pages"
)

// RegisterRoutes adds all page routes to the Echo instance
func RegisterRoutes(e *echo.Echo) {
	e.GET("/", IndexHandler)
	e.GET("/plugin/:id", PluginIdHandler)
}

// IndexHandler handles requests to /
func IndexHandler(c echo.Context) error {
	result, err := pages.IndexHandler(c)
	if err != nil {
		return err
	}
	return pages.Index(result).Render(c.Request().Context(), c.Response().Writer)
}

// PluginIdHandler handles requests to /plugin/:id
func PluginIdHandler(c echo.Context) error {
	result, err := pages.PluginIdHandler(c, c.Param("id"))
	if err != nil {
		return err
	}
	return pages.PluginId(result).Render(c.Request().Context(), c.Response().Writer)
}
